#!/usr/bin/env bash
RC="\e[0m"
RED="\e[31m"
YELLOW="\e[33m"

REQUIREMENTS="rsync zstd"

backupDir() {

    clear

    echo -e "${YELLOW} → Starting backup...${RC}"

    rsync\
        --archive\
        --verbose\
        --recursive\
        --update\
        --links\
        --perms\
        --executability\
        --acls\
        --xattrs\
        --owner\
        --group\
        --devices\
        --specials\
        --times\
        --atimes\
        --delete-before\
        --ignore-errors\
        --compress\
        --compress-choice=zstd\
        --compress-level=9\
        --human-readable\
        --progress\
        --ipv4\
        --exclude-from=${HOME}/.exclude_from_backup\
        / ${BACKUP_DEST}/

}

[[ ${EUID} -ne "0" ]] && { echo -e "${RED} × Run me as root!${RC}"; exit 1; }

for R in "${REQUIREMENTS[@]}"; do

	if ! command -v ${R}>/dev/null; then

        echo -e "${RED} × To run this program, you need ${R}${RC}"

	fi

done

[[ ! -e ${HOME}/.exclude_from_backup ]] && { echo -e "${RED}The file containing the directories to exclude is not present!${RC}"; exit 1; }

[[ -d "${1}" ]] && BACKUP_DEST="${1}" || { echo -e "${RED} × Specify the backup destination.${RC}"; exit 1; }

backupDir|| echo -e "${RED} × Something went wrong!${RC}"
