#!/bin/bash
## Backup important files.

## Set colors.
RC="\e[0m"
BOLD="\e[1m"
GREEN="\e[32m"
RED="\e[31m"
BLUE="\e[34m"

WARN="${RED}${BOLD} [-] ${RC}"
INFO="${BLUE}${BOLD} [*] ${RC}"
GOOD="${GREEN}${BOLD} [+] ${RC}"

BACKUP_FILES()
{
	mkdir -pv ${HOME}/.bak
	[ -f ${HOME}/.pass.gpg ] && cp -Lrv ${HOME}/.pass.gpg ${HOME}/.bak/.pass.gpg.bak
	[ ${?} -eq "0" ] && echo -e "${INFO}-> Password"

	mkdir -pv ${HOME}/.bak
	[ -f ${HOME}/.diary.gpg ] && cp -Lrv ${HOME}/.diary.gpg ${HOME}/.bak/.diary.gpg.bak
	[ ${?} -eq "0" ] && echo -e "${INFO}-> Diary"

	mkdir -pv ${HOME}/.bak
	[ -f ${HOME}/.todo.gpg ] && cp -Lrv ${HOME}/.todo.gpg ${HOME}/.bak/.todo.gpg.bak
	[ ${?} -eq "0" ] && echo -e "${INFO}-> Todo"

	mkdir -pv ${HOME}/.bak
	[ -f ${HOME}/.note.gpg ] && cp -Lrv ${HOME}/.note.gpg ${HOME}/.bak/.note.gpg.bak
	[ ${?} -eq "0" ] && echo -e "${INFO}-> Note"

	mkdir -pv ${HOME}/.bak
	[ -f ${HOME}/.zshrc ] && cp -Lrv ${HOME}/.zshrc ${HOME}/.bak/.zshrc.bak
	[ ${?} -eq "0" ] && echo -e "${INFO}-> Zshrc"

	mkdir -pv ${HOME}/.bak
	[ -f ${HOME}/.bashrc ] && cp -Lrv ${HOME}/.bashrc ${HOME}/.bak/.bashrc.bak
	[ ${?} -eq "0" ] && echo -e "${INFO}-> Bashrc"

	mkdir -pv ${HOME}/.bak
	[ -f ${HOME}/.nanorc ] && cp -Lrv ${HOME}/.nanorc ${HOME}/.bak/.nanorc.bak
	[ ${?} -eq "0" ] && echo -e "${INFO}-> Nanorc"

	mkdir -pv ${HOME}/.bak
	[ -f ${HOME}/Documents/Monero/${USER}/${USER}.keys ] && cp -Lrv ${HOME}/Documents/Monero/${USER}/${USER}.keys ${HOME}/.bak/${USER}.keys.bak
	[ ${?} -eq "0" ] && echo -e "${INFO}-> XMR keys"

	mkdir -pv ${HOME}/.bak
	[ -f ${HOME}/Documents/Monero/${USER}/${USER} ] && cp -Lrv ${HOME}/Documents/Monero/${USER}/${USER} ${HOME}/.bak/${USER}.bak
	[ ${?} -eq "0" ] && echo -e "${INFO}-> XMR data"

	mkdir -pv ${HOME}/.bak
	[ -f ${HOME}/Documents/Monero/${USER}/seed.gpg ] && cp -Lrv ${HOME}/Documents/Monero/${USER}/seed.gpg ${HOME}/.bak/${USER}.bak
	[ ${?} -eq "0" ] && echo -e "${INFO}-> XMR data"
}

echo -e "\n${INFO}Starting files backup...\n"
BACKUP_FILES
[ ${?} -eq "0" ] && echo -e "\n${GOOD}Files backup done!\n" || echo -e "\n${WARN}Something went wrong!\n"
