#!/bin/bash
# Backup system and VMs with rsync.
clear

# Set color
RESET_COLOR="\e[0m"
BOLD="\e[1m"
YELLOW="\e[33m"
RED="\e[31m"
GREEN="\e[32m"
CYAN="\e[36m"

echo -e "You are on ${HOSTNAME}"
echo -e "We are the $(date '+%A, %e %B %Y')"
echo -e "It's $(date '+%H:%M:%S')"

# Check if root
if [ "$EUID" -ne 0 ]
    then
        echo -e "${RED}This script must be runned as root${RESET_COLOR}"
        exit
fi

# Requirements:
# - Check if veracrypt-console is installed.

# No VMs folder present in home -> check for system backup folder.
# Vms folder present in home -> check for VMs folder backup.

# Ask for disk (system & VMs) password and store it in a variable.
# Mount VMs backup disk to ideapad.
# Mount system backup disk to thinkpad.

# Set path
VMS_DIR="/home/lespink/VirtualBox-VMs"
SYSTEM_DIR="/"

if [[ ${HOSTNAME} == "thinkpad" ]]
	then
		echo -e "${YELLOW}Is the SSH server enabled ?${RESET_COLOR}"
		read SSH_SERVER_ENABLED
			if [[ ${SSH_SERVER_ENABLED} == n ]]
				then
					service ssh start
			fi
fi

if [[ -n "$(ls -A ${VMS_DIR} 2>/dev/null)" ]]
	then
		echo -e "\n${YELLOW}VMs is located at ${BOLD}${VMS_DIR}.${RESET_COLOR}"
		echo -e "${YELLOW}System is mounted on ${BOLD}${SYSTEM_DIR}.${RESET_COLOR}"
		echo -e "${YELLOW}Is this information correct ? (Y/n)${RESET_COLOR}"
		read -s CORRECT_INFO
			if [[ ${CORRECT_INFO} == "n" ]]
				then
					echo -e "\n${YELLOW}Exiting...${RESET_COLOR}"
					exit 0
				else
					echo -e "${YELLOW}The following directory will be excluded from backup :${RESET_COLOR}"
					echo -e "${CYAN}$(cat $HOME/.exclude_from_backup)${RESET_COLOR}"
					echo -e "\n${YELLOW}Are you okay with that ?${RESET_COLOR}"
					read -s CORRECT_INFO
						if [[ ${CORRECT_INFO} == "n" ]]
							then
								exit 0
							else
								echo -e "\n${GREEN}Well, starting virtual machines backup...${RESET_COLOR}"
								rsync -av  /home/lespink/VirtualBox-VMs/ /mnt/VirtualBox-VMs/ --delete-after --progress
								echo -e "\n${GREEN}Starting system backup...${RESET_COLOR}"
								# Is root login needed ?
								rsync -av --exclude-from=/root/.exclude_from_backup / lespink@thinkpad:/mnt/Backup-Ideapad --delete-after --progress

						fi
			fi
	else
		echo -e "\n${RED}Virtual Machines directory not found on this system !${RESET_COLOR}"
		echo -e "\n${YELLOW}System is mounted on ${BOLD}${SYSTEM_DIR}.${RESET_COLOR}"
		echo -e "${YELLOW}Is this information correct ? (Y/n)${RESET_COLOR}"
		read -s CORRECT_INFO
			if [[ ${CORRECT_INFO} == "n" ]]
				then
					echo -e "\n${YELLOW}Exiting...${RESET_COLOR}"
					exit 0
				else
					echo -e "${YELLOW}The following directory will be excluded from backup :${RESET_COLOR}"
					echo -e "${CYAN}$(cat $HOME/.exclude_from_backup)${RESET_COLOR}"
					echo -e "\n${YELLOW}Are you okay with that ?${RESET_COLOR}"
					read -s CORRECT_INFO
						if [[ ${CORRECT_INFO} == "n" ]]
							then
								exit 0
							else
								echo -e "\n${GREEN}Well, starting system backup...${RESET_COLOR}"
								rsync -av --exclude-from=/root/.exclude_from_backup / /mnt/Backup-Thinkpad --delete-after --progress
						fi
			fi

fi
