#!/bin/bash
## Backup /home with zip.

TO_BACKUP="/home/${USER}"
BACKUP_DIR="/backup"
BACKUP_FILE="${BACKUP_DIR}/home-${USER}-${HOST}_$(date '+%d-%b-%y').zip"

CREATE_BACKUP()
{
	zip -9 -rv ${BACKUP_FILE} ${TO_BACKUP}
}

UPDATE_BACKUP()
{
	zip -9 -durfy ${BACKUP_FILE} ${TO_BACKUP}
}

if ! which zip > /dev/null
	then
		echo "Zip is not installed!"
		exit 1
	else
		mkdir -p ${BACKUP_DIR}
		if [[ -f ${BACKUP_FILE} ]]
			then
				echo "Updating backup..."
				UPDATE_BACKUP
				echo "Done!"
			else
				echo "Creating backup..."
				CREATE_BACKUP
				echo "Done!"
		fi
fi
