#!/bin/bash
## Update my git repository.

## TODO:
## - Check if git is installed.
## - Clean this mess.

GREEN="\e[32m"
RED="\e[31m"
RESET_COLOR="\e[0m"

CWD=$(pwd)
USER_HOME="/home/lespink"
REPOS_LOCATION="/opt/My-Repo/"

## Check if root
if [ "$EUID" -ne 0 ]
	then
		echo -e "${RED}This script must be runned as root!${RESET_COLOR}"
		exit 1
	else
		if [[ ${1} == "link" ]]
			then
				## User config link
				rm -r ${USER_HOME}/.config/bpytop
				ln -svf /opt/My-Repo/Configs/bpytop ${USER_HOME}/.config/
				rm -r ${USER_HOME}/.config/htop
				ln -svf /opt/My-Repo/Configs/htop ${USER_HOME}/.config/
				ln -svf /opt/My-Repo/Configs/dot-files/.* ${USER_HOME} 2>/dev/null
				## Root config link
				rm -r ${HOME}/.config/bpytop
				ln -svf /opt/My-Repo/Configs/bpytop ${HOME}/.config/
				rm -r ${HOME}/.config/htop
				ln -svf /opt/My-Repo/Configs/htop ${HOME}/.config/
				ln -svf /opt/My-Repo/Configs/dot-files/.* ${HOME} 2>/dev/null
				## Script link
				ln -svf /opt/My-Repo/Updating/update-* /bin/
				ln -svf /opt/My-Repo/Utilities/* /bin/
			else
				if [[ -f ${USER_HOME}/.git-credentials ]]
					then
						cd ${REPOS_LOCATION}
						## Search for GIT repos.
						for GIT_PATH in $(find ${REPOS_LOCATION} -type d -name ".git" 2>/dev/null)
							do
								cd ${GIT_PATH}
								echo -e "\n${BLUE}${BOLD}${GIT_LOCATION}${RESET_COLOR}"
								cd ..
								git config pull.rebase false
								## Pull change
								git pull
								## Add files to the repo
								git add -v .*
								git add -v *
								## Commit change
								git commit -a
								git push -v
								## Pull change
								git pull
								## Add files to the repo
								git add -v .*
								## Commit change
								git commit -a
								git push -v
								cd ${CWD}
						done
					else
						echo -e "${RED}Git credentials not found!${RESET_COLOR}"
				fi
		fi
fi
